version: 2.1
jobs:

  build:
    docker: # run the steps with Docker
      - image: circleci/node:10.16
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: Update NPM
          command: sudo npm install -g npm@latest
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  deploy:
    steps:
      - run:
          name: Install awscli
          command: sudo npm -g awscli@latest
      - run:
          name: Deploy to S3
          command: aws s3 sync ./build s3://${BUCKET_NAME} --delete
      - run:
          name: Invalidate cache
          command: aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'

    docker:
      - image: circleci/node:10.16
    steps:
      - aws-s3/sync:
          from: build
          to: s3://${BUCKET_NAME}
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
      - aws-s3/copy:
          from: bucket/build_asset.txt
          to: 's3://my-s3-bucket-name'
          arguments: '--dryrun'
  