const {
    REACT_APP_PHONE_NUMBER,
    REACT_APP_EMAIL,
    REACT_APP_YOUTUBE_CHANNEL,
    REACT_APP_LINKEDIN,
    REACT_APP_GITHUB
} = process.env;

export default {
    REACT_APP_PHONE_NUMBER,
    REACT_APP_EMAIL,
    REACT_APP_YOUTUBE_CHANNEL,
    REACT_APP_LINKEDIN,
    REACT_APP_GITHUB
};