const {
    REACT_APP_PHONE_NUMBER,
    REACT_APP_EMAIL,
    REACT_APP_YOUTUBE_CHANNEL,
    REACT_APP_LINKEDIN,
    REACT_APP_GITHUB
} = process.env;

export default {
    PHONE_NUMBER: REACT_APP_PHONE_NUMBER,
    EMAIL: REACT_APP_EMAIL,
    YOUTUBE_CHANNEL: REACT_APP_YOUTUBE_CHANNEL,
    LINKEDIN: REACT_APP_LINKEDIN,
    GITHUB: REACT_APP_GITHUB
};